# Copyright 2026 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build stage
FROM golang:1.25-alpine AS builder

# Use Aliyun mirror for faster downloads in China
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

WORKDIR /workspace

COPY go.mod go.sum ./
RUN GOPROXY=https://goproxy.cn,direct go mod download

COPY cmd/image-committer-azure/ cmd/image-committer-azure/
COPY pkg/imagecommitter/ pkg/imagecommitter/
COPY internal/snapshot/ internal/snapshot/
COPY cmd/image-committer/ cmd/image-committer/
COPY cmd/qemu-checkpoint-helper/ cmd/qemu-checkpoint-helper/
COPY cmd/vmstate-loader/ cmd/vmstate-loader/

RUN CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/image-committer ./cmd/image-committer-azure/
RUN CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/image-committer-qemu ./cmd/image-committer/ && \
    CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/qemu-checkpoint-helper ./cmd/qemu-checkpoint-helper/ && \
    CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/vmstate-loader ./cmd/vmstate-loader/

# QEMU uses the standard worker and nerdctl. The commit Job security context
# overrides the image's nonroot default to access the host containerd socket.
FROM alpine:3.22
RUN apk add --no-cache ca-certificates nerdctl

COPY --from=builder /usr/local/bin/image-committer /usr/local/bin/image-committer
COPY --from=builder /usr/local/bin/image-committer-qemu /usr/local/bin/image-committer-qemu
COPY --from=builder /usr/local/bin/qemu-checkpoint-helper /usr/local/bin/qemu-checkpoint-helper
COPY --from=builder /usr/local/bin/vmstate-loader /usr/local/bin/vmstate-loader
USER 65532:65532

WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/image-committer"]
